### ISSUE TITLE
Scroll indicator

### ISSUE THREAD

**Issue by MahmoudiOussama** [HuanHaiLiuXin/CoolViewPager#2]
Could we please have a scroll indicator, the small Dots to indicator the number of images displayed, and the position of the current displayed one.

Like in this library : 
https://github.com/therealshabi/AutoImageFlipper?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=6134

**Comment by HuanHaiLiuXin** [comment]
Thanks for you advice!
I have considered this feature when i wrote this library,but it's not convinient when you want to modify the style of the indicator,and in fact viewpager and indicator are 2 seprated views,we may not write them in one view,and it's inconsistent with the principle of low coupling.
